name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Black
      run: pip install black

    - name: Run Black
      run: black --check .

    - name: Install Docker Compose
      uses: docker/setup-buildx-action@v2

    - name: Build Docker containers
      run: docker compose build

    - name: Run tests
      run: docker compose run tests